"""Regenerate paper/results.tex from saved experiment artifacts.

Reads: data/split.json, data/label_audit.json, experiments/uncertainty.json,
logs/<primary>/evaluation/evaluation_report_<role>.json, train summaries.
Every manuscript number flows through here; nothing is hand-transcribed.

Usage: python scripts/update_paper_numbers.py --primary v2_free_s0 --role val
       (--role test only for the final locked evaluation)
"""

import argparse
import json
import os

import numpy as np


def sload(path, default=None):
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return default


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--primary", required=True)
    ap.add_argument("--role", default="val")
    args = ap.parse_args()

    split = sload("data/split.json", {})
    audit = sload("data/label_audit.json", {"cohorts": {}})
    unc = sload("experiments/uncertainty.json", {"models": {}})
    rep = sload(f"logs/{args.primary}/evaluation/evaluation_report_{args.role}.json")

    n_shots = sum(len(split.get(k, [])) for k in ("train", "val", "test"))

    vals = {
        "nShots": n_shots,
        "nTrain": len(split.get("train", [])),
        "nVal": len(split.get("val", [])),
        "nTest": len(split.get("test", [])),
        "nTrans": len(audit["cohorts"].get("confirmed_transition", [])),
        "nNoTrans": len(audit["cohorts"].get("confirmed_negative", [])),
    }

    lap = unc.get("models", {}).get(args.primary, {}).get("laplace", {})
    if lap:
        vals["resBeta"] = f"{lap['beta']:.2f}"
        vals["resBetaSE"] = f"{lap['beta_se']:.2f}"
        vals["resPbetaPos"] = f"{lap['P(beta>0)_laplace']:.2f}"
        d = lap.get("derived", {})
        s = lap.get("derived_se", {})
        vals["resFoldHigh"] = f"{d.get('alpha_fold', float('nan')):.3f} \\pm {s.get('alpha_fold', float('nan')):.3f}"
        vals["resPthr"] = f"{d.get('P_thr_MW', float('nan')):.1f} \\pm {s.get('P_thr_MW', float('nan')):.1f}"

    boot = unc.get("models", {}).get(args.primary, {}).get("auc_bootstrap", {})
    if boot.get("ci95"):
        vals["resAUCmed"] = f"{boot['median_auc']:.2f}"
        vals["resAUCci"] = f"[{boot['ci95'][0]:.2f}, {boot['ci95'][1]:.2f}]"

    if rep:
        tts = [abs(m["transition_timing"]["transition_time_error_s"]) for m in rep["shot_metrics"].values()
               if m.get("transition_timing") and np.isfinite(m["transition_timing"].get("transition_time_error_s", float("nan")))]
        if tts:
            vals["resTTmed"] = f"\\SI{{{np.median(tts)*1000:.0f}}}{{ms}}"
        vals["resMAE"] = f"\\SI{{{rep['overall_metrics']['annulus_mean_mae_eV']:.0f}}}{{eV}}"

    summ = sload(f"models/{args.primary}/train_summary.json", {})
    # parameter counts
    try:
        import yaml, jax, equinox as eqx
        jax.config.update("jax_enable_x64", True)
        import sys
        sys.path.insert(0, ".")
        from fusion_ode_identification.model import build_hybrid_model
        cfg = yaml.safe_load(open("config/config.yaml"))
        m = build_hybrid_model(cfg, jax.random.PRNGKey(0))
        count = lambda tree: sum(x.size for x in jax.tree_util.tree_leaves(eqx.filter(tree, eqx.is_inexact_array)))
        vals["resNsource"] = f"{count(m.nn):,}"
        vals["resNhead"] = f"{count(m.latent.dalpha_head):,}"
    except Exception:
        pass

    keys = ["nShots", "nTrain", "nVal", "nTest", "nTrans", "nNoTrans", "resBeta", "resBetaSE",
            "resPbetaPos", "resTau", "resFoldHigh", "resPthr", "resPback", "resAUCmed", "resAUCci",
            "resTTmed", "resMAE", "resNsource", "resNhead"]
    with open("paper/results.tex", "w") as f:
        f.write(f"% Generated by scripts/update_paper_numbers.py (primary={args.primary}, role={args.role}).\n")
        f.write("% Do not edit by hand.\n")
        for k in keys:
            f.write(f"\\newcommand{{\\{k}}}{{{vals.get(k, '--')}}}\n")
    print(json.dumps({k: str(v) for k, v in vals.items()}, indent=1))


if __name__ == "__main__":
    main()
